-- Create user table
CREATE TABLE USER(ID INT AUTO_INCREMENT, USER_NAME VARCHAR(100), EMAIL_ADDRESS VARCHAR(100), PHONE_NUMBER VARCHAR(100));
-- Create game table
CREATE TABLE GAME(ID INT AUTO_INCREMENT, GAME_ID_OWNER_PHONE_NUMBER VARCHAR(100), GAME_ID_ICON VARCHAR(100), GAME_STATUS VARCHAR(100), GAME_TITLE VARCHAR(100));
